### ISSUE TITLE
Explosions destroy XP orbs?

### ISSUE THREAD

**Issue by setzke** [alessandrv/alessandrv-enchantments#9] opened 2024-01-08 05:40 UTC
Hey, playing in 1.20.2 on ver 1.5.1. Mod newly added to the server.

I noticed my zombie spawner dropping a lot less XP when I have a large number of zombies built up. Usually one of them seems to have explosive armor on, because there's an explosion when I hit them. Are these explosions destroying the XP orbs that drop?

**Comment by alessandrv** [comment] 2024-02-04 18:26
Hello, sorry for late reply. Issue has been fixed and now explosions caused by the enchantment no longer destroy both items and xp. Will be fixed in next release, probably today.

**Closed as completed by alessandrv** 2024-02-04 18:26 UTC
